%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/rolling/.*$
%global __requires_exclude_from ^/opt/ros/rolling/.*$

%global __cmake_in_source_build 1

Name:           ros-rolling-open-manipulator-collision
Version:        4.1.0
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS open_manipulator_collision package

License:        Apache 2.0
URL:            http://wiki.ros.org/open_manipulator
Source0:        %{name}-%{version}.tar.gz

Requires:       eigen3-devel
Requires:       fcl-devel
Requires:       ros-rolling-kdl-parser
Requires:       ros-rolling-rclcpp
Requires:       ros-rolling-sensor-msgs
Requires:       ros-rolling-std-msgs
Requires:       ros-rolling-urdf
Requires:       ros-rolling-visualization-msgs
Requires:       ros-rolling-ros-workspace
BuildRequires:  eigen3-devel
BuildRequires:  fcl-devel
BuildRequires:  ros-rolling-ament-cmake
BuildRequires:  ros-rolling-kdl-parser
BuildRequires:  ros-rolling-rclcpp
BuildRequires:  ros-rolling-sensor-msgs
BuildRequires:  ros-rolling-std-msgs
BuildRequires:  ros-rolling-urdf
BuildRequires:  ros-rolling-visualization-msgs
BuildRequires:  ros-rolling-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
This package implements a self-collision detection system for the follower robot
during leader-follower teleoperation. Its primary purpose is to enhance safety
by detecting potential self-collisions in real time while the robot is being
remotely operated.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/rolling/setup.sh" ]; then . "/opt/ros/rolling/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/rolling" \
    -DAMENT_PREFIX_PATH="/opt/ros/rolling" \
    -DCMAKE_PREFIX_PATH="/opt/ros/rolling" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/rolling/setup.sh" ]; then . "/opt/ros/rolling/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/rolling/setup.sh" ]; then . "/opt/ros/rolling/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/rolling

%changelog
* Mon Oct 27 2025 Pyo <pyo@robotis.com> - 4.1.0-1
- Autogenerated by Bloom

* Thu Aug 14 2025 Pyo <pyo@robotis.com> - 4.0.7-1
- Autogenerated by Bloom

* Wed Jul 16 2025 Pyo <pyo@robotis.com> - 4.0.6-1
- Autogenerated by Bloom

* Tue Jul 08 2025 Pyo <pyo@robotis.com> - 4.0.5-1
- Autogenerated by Bloom

* Tue Jun 24 2025 Pyo <pyo@robotis.com> - 4.0.1-1
- Autogenerated by Bloom

* Fri Jun 20 2025 Pyo <pyo@robotis.com> - 4.0.0-1
- Autogenerated by Bloom

* Fri Jun 13 2025 Pyo <pyo@robotis.com> - 3.3.0-1
- Autogenerated by Bloom

