%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/rolling/.*$
%global __requires_exclude_from ^/opt/ros/rolling/.*$

Name:           ros-rolling-open-manipulator-teleop
Version:        4.1.2
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS open_manipulator_teleop package

License:        Apache License 2.0
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-rolling-control-msgs
Requires:       ros-rolling-rclpy
Requires:       ros-rolling-sensor-msgs
Requires:       ros-rolling-std-msgs
Requires:       ros-rolling-trajectory-msgs
Requires:       ros-rolling-ros-workspace
BuildRequires:  python%{python3_pkgversion}-devel
BuildRequires:  ros-rolling-control-msgs
BuildRequires:  ros-rolling-rclpy
BuildRequires:  ros-rolling-ros-workspace
BuildRequires:  ros-rolling-sensor-msgs
BuildRequires:  ros-rolling-std-msgs
BuildRequires:  ros-rolling-trajectory-msgs
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
OpenManipulator teleoperation package

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/rolling/setup.sh" ]; then . "/opt/ros/rolling/setup.sh"; fi
%py3_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/rolling/setup.sh" ]; then . "/opt/ros/rolling/setup.sh"; fi
%py3_install -- --prefix "/opt/ros/rolling"

%if 0%{?with_tests}
%check
# Look for a directory with a name indicating that it contains tests
TEST_TARGET=$(ls -d * | grep -m1 "\(test\|tests\)" ||:)
if [ -n "$TEST_TARGET" ] && %__python3 -m pytest --version; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/rolling/setup.sh" ]; then . "/opt/ros/rolling/setup.sh"; fi
%__python3 -m pytest $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/rolling

%changelog
* Thu Jan 15 2026 Pyo <pyo@robotis.com> - 4.1.2-1
- Autogenerated by Bloom

* Mon Oct 27 2025 Pyo <pyo@robotis.com> - 4.1.0-1
- Autogenerated by Bloom

* Thu Aug 14 2025 Pyo <pyo@robotis.com> - 4.0.7-1
- Autogenerated by Bloom

* Wed Jul 16 2025 Pyo <pyo@robotis.com> - 4.0.6-1
- Autogenerated by Bloom

* Tue Jul 08 2025 Pyo <pyo@robotis.com> - 4.0.5-1
- Autogenerated by Bloom

* Tue Jun 24 2025 Pyo <pyo@robotis.com> - 4.0.1-1
- Autogenerated by Bloom

* Fri Jun 20 2025 Pyo <pyo@robotis.com> - 4.0.0-1
- Autogenerated by Bloom

* Fri Jun 13 2025 Pyo <pyo@robotis.com> - 3.3.0-1
- Autogenerated by Bloom

* Wed Jun 04 2025 Pyo <pyo@robotis.com> - 3.2.4-1
- Autogenerated by Bloom

* Wed Apr 23 2025 Pyo <pyo@robotis.com> - 3.2.2-1
- Autogenerated by Bloom

* Mon Apr 14 2025 Pyo <pyo@robotis.com> - 3.2.1-1
- Autogenerated by Bloom

