%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/kilted/.*$
%global __requires_exclude_from ^/opt/ros/kilted/.*$

%global __cmake_in_source_build 1

Name:           ros-kilted-open-manipulator-gui
Version:        4.1.0
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS open_manipulator_gui package

License:        Apache 2.0
URL:            http://wiki.ros.org/open_manipulator
Source0:        %{name}-%{version}.tar.gz

Requires:       qt5-qtbase
Requires:       qt5-qtbase-devel
Requires:       qt5-qtbase-gui
Requires:       ros-kilted-eigen3-cmake-module
Requires:       ros-kilted-geometry-msgs
Requires:       ros-kilted-moveit-core
Requires:       ros-kilted-moveit-msgs
Requires:       ros-kilted-moveit-ros-planning
Requires:       ros-kilted-moveit-ros-planning-interface
Requires:       ros-kilted-rclcpp
Requires:       ros-kilted-sensor-msgs
Requires:       ros-kilted-std-msgs
Requires:       ros-kilted-ros-workspace
BuildRequires:  qt5-qtbase
BuildRequires:  qt5-qtbase-devel
BuildRequires:  qt5-qtbase-gui
BuildRequires:  ros-kilted-ament-cmake
BuildRequires:  ros-kilted-eigen3-cmake-module
BuildRequires:  ros-kilted-geometry-msgs
BuildRequires:  ros-kilted-moveit-core
BuildRequires:  ros-kilted-moveit-msgs
BuildRequires:  ros-kilted-moveit-ros-planning
BuildRequires:  ros-kilted-moveit-ros-planning-interface
BuildRequires:  ros-kilted-rclcpp
BuildRequires:  ros-kilted-sensor-msgs
BuildRequires:  ros-kilted-std-msgs
BuildRequires:  ros-kilted-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
The OpenMANIPULATOR GUI ROS 2 package enables users to explore Joint Space, Task
Space, and even work with the Task Constructor functionality.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/kilted" \
    -DAMENT_PREFIX_PATH="/opt/ros/kilted" \
    -DCMAKE_PREFIX_PATH="/opt/ros/kilted" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/kilted

%changelog
* Mon Oct 27 2025 Pyo <pyo@robotis.com> - 4.1.0-1
- Autogenerated by Bloom

* Mon Sep 08 2025 Pyo <pyo@robotis.com> - 4.0.8-1
- Autogenerated by Bloom

* Thu Aug 14 2025 Pyo <pyo@robotis.com> - 4.0.7-1
- Autogenerated by Bloom

* Tue Jul 15 2025 Pyo <pyo@robotis.com> - 4.0.6-1
- Autogenerated by Bloom

* Tue Jul 08 2025 Pyo <pyo@robotis.com> - 4.0.5-1
- Autogenerated by Bloom

* Tue Jun 24 2025 Pyo <pyo@robotis.com> - 4.0.1-1
- Autogenerated by Bloom

* Sat Apr 26 2025 Pyo <pyo@robotis.com> - 3.2.2-1
- Autogenerated by Bloom

* Tue Apr 22 2025 Pyo <pyo@robotis.com> - 3.2.1-2
- Autogenerated by Bloom

* Mon Apr 14 2025 Pyo <pyo@robotis.com> - 3.2.1-1
- Autogenerated by Bloom

