controller_manager:
  ros__parameters:
    use_sim_time: True
    update_rate: 400  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

arm_controller:
  ros__parameters:
    use_sim_time: True
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - rh_r1_joint

    interface_name: position

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0 # Defaults to 0.0 (start immediately)
